# Generated by Django 2.1.7 on 2019-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_heading', models.CharField(max_length=250)),
                ('invoice_body', models.TextField()),
            ],
        ),
    ]
